### ISSUE TITLE
Resistors for V1.15 and solidworks file

### ISSUE THREAD

**Issue by thomasrgray** [Karpova-Lab/nosepoke#1]
Hello,

I was wondering if you can post the parts list for the V1.15 version and the solidworks file for the nosepoke body?

**Comment by alustig3** [comment]
Hi,

I don't have a Solidworks file specifically, but a step file, which you should be able to open with Solidworks, can be found [here](https://karpova-lab.github.io/nosepoke/docs/designs/#plastic-nosepoke-body).

I recommend using [PCB v1.17](https://oshpark.com/shared_projects/07c1qRaL) (sorry the [link in the documentation](https://karpova-lab.github.io/nosepoke/docs/designs/#pcbs-and-electronics) is out of date, I will update it soon). The main difference between v1.17 and v1.15 is that the IR emitter LED can now be turned off when not being used, which greatly extends the life of the LED. A BOM for PCB, including resistors, can be found [here(interactive)](https://karpova-lab.github.io/nosepoke/docs/designs/ibom.html) and [here(w/purchase links)](https://karpova-lab.github.io/nosepoke/docs/designs/#pcbs-and-electronics). 

I hope that answers your questions. Don't hesitate to reach out if you have more!

**Comment by alustig3** [comment]
Documentation has been updated with links and images for PCB v1.17 1b5cfa0ab71ac33a03055e42cff861d6122487c5
