### ISSUE TITLE
IR sensor phototransistor is sensitive to visible light

### ISSUE THREAD

**Issue by danielsvedberg** [Karpova-Lab/nosepoke#3]
[The karpova lab BOM](https://karpova-lab.github.io/nosepoke/docs/designs/) lists[PT26-21C/TR8](https://www.digikey.com/products/en?keywords=1080-1386-1-ND) as the specified phototransistor. The [phototransistor documents](https://media.digikey.com/pdf/Data%20Sheets/Everlight%20PDFs/PT26-21C_TR8.pdf) indicate that "The device is Spectrally matched to visible and infrared emitting diode". This means that any ambient light, such as the nosepoke's own white-light LED, may potentially trigger the phototransistor. Typically, IR sensors spec photodiodes/transistors with a dark lens to prevent visible light from triggering the sensor. Is this an issue you have observed / is a visible-light sensitive phototransistor the correct spec, or is there an error?

**Comment by alustig3** [comment]
Thanks for the question. This has not been an issue for us.

When there is nothing in the nosepoke, the phototransistor is already saturated with light from the IR emitter, so adding or removing other light will have no effect.

The irradiance required to get the current flowing well through the phototransitor is actually pretty high. In this case, we achieve it by having a well aligned IR emitter (close to the photransistor's peak spectral sensitivity) shining directly into it (at its peak angular sensitivity). When something is inside the nosepoke and disrupts the light coming from the IR emitter, the decrease in irradiance is drastic. It would be extremely difficult for other light sources to reach the phototransistor with enough power to replace the light that was being shined into the photoransistor by the IR emitter under ideal conditions.
